/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as testsContactLazyTestImport } from './routes/__tests__/contact.lazy.test'

// Create Virtual Routes

const PastLazyImport = createFileRoute('/past')()
const OrderLazyImport = createFileRoute('/order')()
const ContactLazyImport = createFileRoute('/contact')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const PastLazyRoute = PastLazyImport.update({
  id: '/past',
  path: '/past',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/past.lazy').then((d) => d.Route))

const OrderLazyRoute = OrderLazyImport.update({
  id: '/order',
  path: '/order',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/order.lazy').then((d) => d.Route))

const ContactLazyRoute = ContactLazyImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/contact.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const testsContactLazyTestRoute = testsContactLazyTestImport.update({
  id: '/__tests__/contact/lazy/test',
  path: '/contact/lazy/test',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactLazyImport
      parentRoute: typeof rootRoute
    }
    '/order': {
      id: '/order'
      path: '/order'
      fullPath: '/order'
      preLoaderRoute: typeof OrderLazyImport
      parentRoute: typeof rootRoute
    }
    '/past': {
      id: '/past'
      path: '/past'
      fullPath: '/past'
      preLoaderRoute: typeof PastLazyImport
      parentRoute: typeof rootRoute
    }
    '/__tests__/contact/lazy/test': {
      id: '/__tests__/contact/lazy/test'
      path: '/contact/lazy/test'
      fullPath: '/contact/lazy/test'
      preLoaderRoute: typeof testsContactLazyTestImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/contact': typeof ContactLazyRoute
  '/order': typeof OrderLazyRoute
  '/past': typeof PastLazyRoute
  '/contact/lazy/test': typeof testsContactLazyTestRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/contact': typeof ContactLazyRoute
  '/order': typeof OrderLazyRoute
  '/past': typeof PastLazyRoute
  '/contact/lazy/test': typeof testsContactLazyTestRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/contact': typeof ContactLazyRoute
  '/order': typeof OrderLazyRoute
  '/past': typeof PastLazyRoute
  '/__tests__/contact/lazy/test': typeof testsContactLazyTestRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/contact' | '/order' | '/past' | '/contact/lazy/test'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/contact' | '/order' | '/past' | '/contact/lazy/test'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/order'
    | '/past'
    | '/__tests__/contact/lazy/test'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  ContactLazyRoute: typeof ContactLazyRoute
  OrderLazyRoute: typeof OrderLazyRoute
  PastLazyRoute: typeof PastLazyRoute
  testsContactLazyTestRoute: typeof testsContactLazyTestRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  ContactLazyRoute: ContactLazyRoute,
  OrderLazyRoute: OrderLazyRoute,
  PastLazyRoute: PastLazyRoute,
  testsContactLazyTestRoute: testsContactLazyTestRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.jsx",
      "children": [
        "/",
        "/contact",
        "/order",
        "/past",
        "/__tests__/contact/lazy/test"
      ]
    },
    "/": {
      "filePath": "index.lazy.jsx"
    },
    "/contact": {
      "filePath": "contact.lazy.jsx"
    },
    "/order": {
      "filePath": "order.lazy.jsx"
    },
    "/past": {
      "filePath": "past.lazy.jsx"
    },
    "/__tests__/contact/lazy/test": {
      "filePath": "__tests__/contact.lazy.test.jsx"
    }
  }
}
ROUTE_MANIFEST_END */
